"""
Model drift monitoring -- compares live Model A's log loss with its
backtest baseline (data/nfl/drift_baseline.json), and flags when the gap is
large enough to be a real statistical signal rather than small-sample
noise. Live accuracy against data/nfl/calibration.json is still printed for
both models, as information.

Since Stage 33 R4 (experiments/nfl/stage33/registry.json) the flag is on LOG
LOSS. It was on accuracy, which this project's own methodology says cannot
carry a result at this sample size. The rule, registered before any 2026
log loss was computed for it: over every graded live Model A game with a
winner, flag when the lower end of a one-sided 95% bootstrap interval of
the mean per-game log loss is above the baseline, and not before 30 games.
The baseline is the 2022-2025 backtest with the schedule's listed starter
(0.6518), the closest backtest to what v2.5 runs; the lagged-QB figure
(0.6643) is printed beside it.

Why this exists: this project has found three real, silent bugs this
season (a leak in QB rating shrinkage, an unreproducible hyperparameter
decision, and a production pipeline with no scheduled trigger at all) --
all found by someone manually digging in, not by anything automated. This
script is meant to catch the next one earlier: if live performance quietly
diverges from what the backtest promised, that's worth a flag before it
becomes a months-old mystery.

Run standalone: python -m src.sports.nfl.check_drift
Exit code 0 = no concerning drift (or not enough data yet to tell).
Exit code 1 = statistically significant underperformance detected.
"""
import json
import math
from pathlib import Path

import numpy as np

from src.core.runlog import get_logger
from src.sports.nfl.config import BACKTEST_SEASONS
from src.sports.nfl.paths import (  # src/sports/nfl/paths.py, Stage 32 item 15
    DATA_DIR,
    RESULTS_DIR,
    parse_week,
)

log = get_logger(__name__)
MIN_GAMES_TO_TEST = 30  # below this, any gap could easily just be noise
SIGNIFICANCE_Z = 1.96  # two-sided 95% -- consistent with the CIs used everywhere else in this project

# The baseline is the committed backtest artifact, data/nfl/calibration.json --
# the file the page's backtest table and README print, tied to them by
# tests/test_backtest_figures_tie.py. Never a recomputation from live
# results: the comparison target must not move with what is compared
# against it. It moves only when that file is deliberately regenerated by
# src/sports/nfl/research/calibration.py (one commit in its history as of 2026-09-30).
# Until Stage 35 this was config.BACKTEST_ACCURACY, a literal typed in with
# the first upload: 0.628 and 0.682, one game off each way from the file's
# 682 and 742 of 1087, so the drift report quoted a baseline printed nowhere
# else. Since Stage 33 R4 this accuracy baseline is printed as information;
# the flag's log-loss baseline is DRIFT_BASELINE below.
CALIBRATION = DATA_DIR / 'calibration.json'
#: (model in calibration.json, graded-row key, label) for each model watched.
WATCHED = (('model_a', 'model_a_correct', 'Model A'),
           ('model_b', 'model_b_correct', 'Model B'))

#: Stage 33 R4's log-loss baseline and rule, committed, never recomputed
#: from live results. tests/test_check_drift_log_loss.py ties it to the
#: registry and to experiments/nfl/stage5/residuals.json.
DRIFT_BASELINE = DATA_DIR / 'drift_baseline.json'
#: The live probability the log loss is scored on, and the outcome.
LOG_LOSS_PROB = 'model_a_home_win_prob'
EPS = 1e-15


def log_loss_baseline(path: Path | None = None) -> dict:
    """R4's committed baseline and rule. Raises OSError, ValueError or
    KeyError when the file is missing, unreadable or incomplete."""
    spec = json.loads(Path(DRIFT_BASELINE if path is None else path).read_text(encoding='utf-8'))
    for key in ('baseline', 'printed_beside', 'rule'):
        spec[key]  # a KeyError here is the "incomplete" case
    return spec


def per_game_log_loss(records, prob_key=LOG_LOSS_PROB):
    """Per-game log loss of every graded game with a winner. A tie has no
    winner (actual_home_win None) and decides nothing, as in grading."""
    out = []
    for r in records:
        y, p = r.get('actual_home_win'), r.get(prob_key)
        if y not in (0, 1) or p is None:
            continue
        p = min(max(float(p), EPS), 1 - EPS)
        out.append(-math.log(p) if y == 1 else -math.log(1 - p))
    return out


def log_loss_lower_bound(losses, rule):
    """The lower end of a one-sided bootstrap interval of the mean, at the
    rule's level, resampled with the rule's own seed so a rerun is identical."""
    arr = np.asarray(losses, dtype=float)
    rng = np.random.default_rng(rule['seed'])
    idx = rng.integers(0, len(arr), size=(rule['n_resamples'], len(arr)))
    return float(np.percentile(arr[idx].mean(axis=1), (1 - rule['one_sided_level']) * 100))


def check_log_loss(records, spec, label='Model A'):
    """R4: the check that decides the flag. True when it flags."""
    losses = per_game_log_loss(records)
    base, beside, rule = spec['baseline'], spec['printed_beside'], spec['rule']
    log.info(f"\n{label}, log loss (decides the flag; Stage 33 R4):")
    log.info(f"  Live games scored: {len(losses)}")
    if not losses:
        log.info("  No live results with a winner yet -- nothing to check.")
        return False
    mean = sum(losses) / len(losses)
    log.info(f"  Observed log loss: {mean:.4f}")
    log.info(f"  Baseline: {base['value']:.4f} ({base['label']}); "
             f"for reference, {beside['value']:.4f} ({beside['label']})")
    if len(losses) < rule['min_games']:
        log.info(f"  Below {rule['min_games']} games -- too early to test statistically, watching only.")
        return False
    lower = log_loss_lower_bound(losses, rule)
    log.info(f"  One-sided {rule['one_sided_level']:.0%} lower bound: {lower:.4f}")
    if lower > base['value']:
        log.warning(f"  *** DRIFT WARNING: live log loss is significantly above the backtest baseline "
                    f"(lower bound {lower:.4f} > {base['value']:.4f}) ***")
        log.info("  This does not automatically mean something is broken -- real variance happens -- but it's")
        log.info("  a large enough, unlikely-by-chance gap that it's worth a real look, not just noting and moving on.")
        return True
    log.info("  No significant drift detected.")
    return False


def backtest_baseline(path: Path | None = None) -> dict[str, dict]:
    """{model: its backtest metrics} for every watched model, from the
    committed backtest artifact. Raises OSError, ValueError or KeyError when
    the file is missing, unreadable or lacks a watched model."""
    models = json.loads(Path(CALIBRATION if path is None else path).read_text(encoding='utf-8'))['models']
    return {model: models[model]['metrics'] for model, _, _ in WATCHED}


def load_live_results():
    """Loads every graded result file for a season NOT in BACKTEST_SEASONS
    -- i.e., real, live predictions made after the backtest period, not
    the historical games the backtest itself was evaluated on."""
    records = []
    if not RESULTS_DIR.exists():
        return records
    for path in RESULTS_DIR.glob('*_graded.json'):
        parsed = parse_week(path.stem.removesuffix('_graded'))
        if parsed is None:
            continue
        season = parsed[0]
        if season in BACKTEST_SEASONS:
            continue  # this is backtest-period data, not live monitoring data
        with open(path) as f:
            records.extend(json.load(f))
    return records


def one_proportion_z_test(observed_correct, n, expected_p):
    """Standard one-sample z-test for a proportion. Returns (z, is_significant_and_worse).
    No scipy dependency -- this script's only job is to be a reliable
    safety check, so it shouldn't itself depend on anything that could
    fail to be present in a given environment."""
    if n == 0:
        return None, False
    observed_p = observed_correct / n
    se = math.sqrt(expected_p * (1 - expected_p) / n)
    if se == 0:
        return None, False
    z = (observed_p - expected_p) / se
    is_significant_and_worse = z <= -SIGNIFICANCE_Z
    return z, is_significant_and_worse


def check_model(records, key, expected_p, label):
    graded = [r for r in records if r.get(key) is not None]
    n = len(graded)
    correct = sum(r[key] for r in graded)

    log.info(f"\n{label}:")
    log.info(f"  Live games graded: {n}")
    if n == 0:
        log.info("  No live results yet -- nothing to check.")
        return False
    observed_p = correct / n
    log.info(f"  Observed accuracy: {correct}/{n} = {observed_p*100:.1f}%")
    log.info(f"  Backtest baseline: {expected_p*100:.1f}%")

    if n < MIN_GAMES_TO_TEST:
        log.info(f"  Below {MIN_GAMES_TO_TEST} games -- too early to test statistically, watching only.")
        return False

    z, flagged = one_proportion_z_test(correct, n, expected_p)
    log.info(f"  z-score: {z:.2f}" if z is not None else "  z-score: undefined")
    if flagged:
        # Information only since Stage 33 R4: printed, never the flag.
        log.info(f"  Accuracy is significantly below the backtest baseline (z={z:.2f}, "
                 f"threshold={-SIGNIFICANCE_Z}). Information only: accuracy cannot carry a result "
                 "at this sample size, and the flag is on log loss.")
    else:
        log.info("  No significant accuracy gap.")
    return flagged


def main():
    records = load_live_results()
    log.info(f"Loaded {len(records)} live (non-backtest-season) graded predictions.")

    # A missing baseline must not fail the weekly run (drift_alert.py:
    # "It never fails the weekly run"), and must not read as a clean check
    # either: the verdict line says it did not run, and the run summary
    # carries that line and the warning.
    try:
        baseline = backtest_baseline()
        spec = log_loss_baseline()
    except (OSError, ValueError, KeyError) as e:
        log.warning(f"WARNING: no backtest baseline in {CALIBRATION.name} or {DRIFT_BASELINE.name} "
                    f"({type(e).__name__}: {e}); drift not checked.")
        log.info("\n=== DRIFT CHECK: NOT RUN (no backtest baseline) ===")
        return 0

    log.info("\nAccuracy, for information (the flag is on log loss below):")
    for model, key, label in WATCHED:
        check_model(records, key, baseline[model]['accuracy'], label)

    if check_log_loss(records, spec):
        log.info("\n=== DRIFT CHECK: WARNING FLAGGED ===")
        return 1
    log.info("\n=== DRIFT CHECK: OK ===")
    return 0


if __name__ == '__main__':
    import sys
    sys.exit(main())
